version: 2
jobs:
  build:
    docker:
      - image: red56/capybara-webkit-deps
        environment:
          BUNDLE_GITHUB__HTTPS: true
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: root
    working_directory: /root/sample
    steps:
      - checkout
      - run: ruby -v
      - restore_cache:
          keys:
            - sample1-{{ .Branch }}-bundle-{{ checksum "Gemfile.lock" }}
            - sample1-{{ .Branch }}-bundle
      - run:
          name: Bundle Install Ruby Dependencies
          command: gem update bundler && bundle -v && bundle install
      - run: bundle show rails
      - save_cache:
          key: sample1-{{ .Branch }}-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - /root/sample/vendor/bundle
      - save_cache:
          key: sample1-{{ .Branch }}-bundle
          paths:
            - /root/sample/vendor/bundle

      - run:
          name: Create DB and load schema
          command: cp config/database.circle.yml config/database.yml && bundle exec rake db:create db:schema:load --trace


      - run:
          name: knapsack pro regular mode with xvfb
          command: |
            RAILS_ENV=test
            xvfb-run -a bundle exec rake "knapsack_pro:rspec[--format d --format RspecJunitFormatter --out /tmp/tests/rspec/junit.xml]"
      #- run:
          #name: knapsack pro regular mode without xvfb
          #command: |
            #RAILS_ENV=test
            #bundle exec rake "knapsack_pro:rspec[--format d --format RspecJunitFormatter --out /tmp/tests/rspec/junit.xml]"


      - run:
          name: knapsack pro queue with xvfb
          command: |
            RAILS_ENV=test
            xvfb-run -a bundle exec rake "knapsack_pro:queue:rspec[--format d --format RspecJunitFormatter --out /tmp/tests/rspec/junit.xml]"
      #- run:
          #name: knapsack pro queue without xvfb
          #command: |
            #RAILS_ENV=test
            #bundle exec rake "knapsack_pro:queue:rspec[--format d --format RspecJunitFormatter --out /tmp/tests/rspec/junit.xml]"



      - store_test_results:
          path: /tmp/tests
      - store_artifacts:
          path: /tmp/rspec
          destination: rspec
      - store_artifacts:
          path: /root/sample/tmp/capybara
          destination: screenshots
