development:
  adapter: postgresql
  database: sample_development
  username: root
  password:
  host: localhost
  encoding: utf8

test:
  adapter: postgresql
  database: sample_test
  username: root
  password:
  host: localhost
  encoding: utf8
